name: proddit
url: http://proddit.com
description: arată ca un notepad

permalink: /:year/:month/:day/:title/
paginate: 10
#highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

host: 0.0.0.0

gems: [jekyll-paginate]
